export const GET_HOME_PROPERTY_REQUEST = 'GET_HOME_PROPERTY_REQUEST';
export const GET_HOME_PROPERTY_SUCCESS = 'GET_HOME_PROPERTY_SUCCESS';
export const GET_HOME_PROPERTY_FAIL = 'GET_HOME_PROPERTY_FAIL';

export const PROPERTY_DETAIL_SUCCESS = 'PROPERTY_DETAIL_SUCCESS';
export const PROPERTY_DETAIL_FAIL = 'PROPERTY_DETAIL_FAIL';

export const ADD_AMENITIES = 'ADD_AMENITIES';
export const COUNTERY = 'COUNTERY';
export const PRICE = 'PRICE';
export const AREA = 'AREA';
export const BEDS = 'BEDS';
export const BATHS = 'BATHS';
export const STATUS = 'STATUS';

