export const GET_HOME_PROPERTY_REQUEST = 'GET_HOME_PROPERTY_REQUEST';
export const GET_HOME_PROPERTY_SUCCESS = 'GET_HOME_PROPERTY_SUCCESS';
export const GET_HOME_PROPERTY_FAIL = 'GET_HOME_PROPERTY_FAIL';

export const PROPERTY_DETAIL_SUCCESS = 'PROPERTY_DETAIL_SUCCESS';
export const PROPERTY_DETAIL_FAIL = 'PROPERTY_DETAIL_FAIL';
